// import 'redux';
import 'masonry-layout';
import 'imagesloaded';
import 'blueimp-gallery';
import './js/gallery-initial.js';
//import 'core-js/stable';
//import 'regenerator-runtime/runtime';

// import './js/utilities.js';
// import './js/state-management/store.js';
// import './js/lazy-load.js';
// import './js/jquery.js';
// import './js/wp-embed.js';
// import './js/disqus.js';
// import './js/social-events.js';
// import './js/slider/slider.js';
// //import './js/form-action.js';
// import './js/ui/chroma.js';
// import './js/ui/chroma-infinite.js';
// import './js/ui/chroma-scroll-anchors.js';
// import './js/gallery-initial.js';
// import './ad-loaders/ad-appender.js';
// import './ad-loaders/rev-content.js';
// import './js/wallpapers/wallscript.js';
// import './js/like-button.js';

// import './sass/social-share-fix/share-fix.sass';
// import './sass/_INDEX.scss';
// import './wallsass/wallpaper.scss';
// import './giveaway-widget-external/gawidget.scss';
// import './sass/colors.scss';